name: 'AWS ECR Images Deploy'
description: 'Automatically deploys deploys image(s) to aws Elastic Container Registry-ECR'
inputs:
    access_key_id:
        description: 'AWS access key id'
        required: true
    secret_access_key:
        description: 'AWS secret acess key'
        required: true
    region:
        description: 'AWS Region whose servers you want to send your requests to by defaul. Region close to you'
        required: true
    aws_account_id:
        description: 'AWS account id'
        required: true
    repo_name:
        description: 'AWS ECR Repository name'
        required: false
    scan_on_push:
        description: 'Scan image on pushing to ECR'
        required: false
        default: true
    image_name:
        description: 'Docker image name'
        required: true
    use_compose:
        description: 'Build from docker compose file'
        required: false
        default: false
    docker_path:
        description: 'Path to Dockerfile or docker-compose file'
        default: './'
    repo_uri:
        description: 'ECR Repository URI'
        required: false
    tag_name:
        description: 'ECR Repository Image tag name'
        required: false
        default: 'latest'
    force_push:
        description: 'Force push to AWS ECR if there are conflicts or git fast forwards issues'
        required: false
        default: false
    working-directory:
        description: 'The directory for the commands to execute in'
        default: './'
outputs:
    status:
        description: "Status of the action"
runs:
    using: "node12"
    main: "index.js"


